auth/urls.py
from django.urls import path
from .import views

app_name ='auth'

urlpatterns = [
    path('login/',views.login_user,name='login_page'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout_user,name='logout')
]

recipeproj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('recipes.urls')),
    path('auth/',include('auth.urls',namespace='auth')),
    # path('__debug__/', include('debug_toolbar.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('',views.index,name='home'),
    path('entrees/',views.entree_page,name='entrees'),
    path('desserts/',views.desserts_page,name='desserts'),
    path('add_recipe/',views.add_recipe,name='add_recipe'),
    path('appetizers/',views.appetizers,name='appetizers'),
    path('recipes/<int:pk>/',views.RecipeDetailView.as_view(),name='recipe_detail'),
    path('recipes/<int:pk>/update/',views.RecipeUpdateView.as_view(),name='recipe_update'),
    path('recipes/<int:pk>/delete/',views.RecipeDeleteView.as_view(),name='recipe_delete'),
]

recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model

User =get_user_model()
# Create your models here.

class RecipeChoices(models.TextChoices):
    DESSERTS = "desserts" , "D"
    ENTREES = "entrees" , "E"
    APPETIZERS = "appetizers" , "A"

class Recipe(models.Model):
    name = models.CharField(max_length=50)
    detail =models.TextField()
    date_created =models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=10,choices=RecipeChoices.choices,default=RecipeChoices.APPETIZERS)
    image = models.ImageField(upload_to="images/",default="default.jpg")
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

    class Meta:
        ordering = ['-date_created']

recipes/forms.py
from .models import Recipe
from django import forms


class RecipeCreatForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name','detail','category','image']
        widgets ={
            'name':forms.TextInput(attrs={'class':'input'}),
            'detail':forms.Textarea(attrs={'class':'input','rows':10}),
            # 'category':forms.ChoiceField(),
            'image':forms.FileInput(attrs={'class':'file-input'}),
        }

recipes/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Recipe
from .forms import RecipeCreatForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import DeleteView,DetailView,UpdateView

# Create your views here.




def index(request):
    recipes = Recipe.objects.all()
    context = {
        'recipes':recipes,
        'name':"Rina"
    }
    return render(request,'home.html',context)


def entree_page(request):
    return render(request,'Entrees.html',
                  {'entrees':Recipe.objects.filter(category='entrees')})


def desserts_page(request):
    return render(request,'desserts.html',
                  {'desserts':Recipe.objects.filter(category='desserts')})


def appetizers(request):
    
    return render(request,'appetizers.html',
                  {'appetizers':Recipe.objects.filter(category='appetizers')})

@login_required
def add_recipe(request):
    form =  RecipeCreatForm()

    if request.method =='POST':
        form= RecipeCreatForm(request.POST,request.FILES)

        if form.is_valid():
            form_obj = form.save(commit=False)

            form_obj.created_by = request.user

            form_obj.save()

            return redirect(reverse('home'))


    context ={
        'form':form
    }
    return render(request,'add_recipe.html',context)


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "detail.html"
    context_object_name = 'recipe'



class RecipeUpdateView(UpdateView):
    model = Recipe
    template_name = "update.html"
    success_url = '/'
    fields = ['name','detail']


class RecipeDeleteView(DeleteView):
    model = Recipe
    template_name = "delete.html"
    success_url = '/'

templates/Entrees.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<main>
    <section id="recipes">
        <div class="recipe-list">
            
            {% for recipe in entrees %}
            <div class="card">
                <div class="card-img">
                    
                        <img src="{{recipe.image.url}}">
                    </a>
                </div>
                <div class="card-detail">
                    <a href="{% url 'recipe_detail' pk=recipe.id%}">
                        <h3>{{recipe.name}}</h3>
                    </a>
                    <p>{{recipe.detail|truncatewords:20}}</p>
                </div>
            </div>
            {% endfor %}
                
        </div>      
    </section>
</main>

{%endblock content%}

templates/add_recipe.html
{%extends 'base.html'%}
{%block content%}
<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        <h1>Add Recipe</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add recipe" class="btn-primary">
    </form>
</div>
{%endblock content%}

templates/appetizers.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<main>
    <section id="recipes">
        <div class="recipe-list">
            
            {% for recipe in appetizers %}
            <div class="card">
                <div class="card-img">
                    
                        <img src="{{recipe.image.url}}">
                    </a>
                </div>
                <div class="card-detail">
                    <a href="{% url 'recipe_detail' pk=recipe.id%}">
                        <h3>{{recipe.name}}</h3>
                    </a>
                    <p>{{recipe.detail|truncatewords:20}}</p>
                </div>
            </div>
            {% endfor %}
                
        </div>      
    </section>
</main>

{%endblock content%}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
	<title>Recipe App</title>
	<link rel="stylesheet" href="{%static 'index.css'%}">
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body>
	<header class="bg-light">
		<h1><a href="{% url 'home' %}">Recipe App</a></h1>

		<nav>
			<ul>
				
				{% if user.is_authenticated %}
					<li><a href="{%url 'home'%}">Home</a></li>
					<li><a href="{%url 'add_recipe'%}">Add Recipe</a></li>
					<li><a href="{%url 'auth:logout'%}">Logout</a></li>
				{% else %}
					<li><a href="{%url 'home'%}">Home</a></li>
					<li><a href="{%url 'auth:register'%}">Sign Up</a></li>
					<li><a href="{%url 'auth:login_page'%}">Login</a></li>
				{% endif %}
					
			</ul>
		</nav>
		<form>
			<input type="text" placeholder="Search for recipes..." class="search-input">
			<button type="submit"  id="search" class="btn-primary btn">Search</button>
		</form>
	</header>
  <div class="main">
	{% block content%}
    {%endblock content%}
  </div>
    <footer>
		<section id="categories">
			<h2>Categories</h2>
			<ul>
				<li><a href="{%url 'appetizers'%}">Appetizers</a></li>
				<li><a href="{%url 'entrees'%}">Entrees</a></li>
				<li><a href="{%url 'desserts'%}">Desserts</a></li>
			</ul>
		</section>
		<p>Copyright © Recipe App</p>
	</footer>
	<script src="index.js"></script>
</body>

</html>

templates/delete.html
{% extends 'base.html' %}
{% block content %}
    <h1>Delete Recipe</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" class="delete-btn">
        <a href="{% url 'home' %}" class="btn-primary">Cancel</a>
    </form>
{% endblock content %}
    

templates/desserts.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<main>
    <section id="recipes">
        <div class="recipe-list">
            
            {% for recipe in desserts %}
            <div class="card">
                <div class="card-img">
                    
                        <img src="{{recipe.image.url}}">
                    </a>
                </div>
                <div class="card-detail">
                    <a href="{% url 'recipe_detail' pk=recipe.id%}">
                        <h3>{{recipe.name}}</h3>
                    </a>
                    <p>{{recipe.detail|truncatewords:20}}</p>
                </div>
            </div>
            {% endfor %}
                
        </div>      
    </section>
</main>

{%endblock content%}

templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <center>
        <img src="{{recipe.image.url}}" alt="recipe image" width="400" height="400">
    </center>
    <h1>{{ recipe.name }}</h1>
    <br>
    <span><b>Created By: {{recipe.created_by}}</b></span>
    <br>

    {{ recipe.detail }}
    <br>
    <br>
    <div class="options">
        {% if recipe.created_by == user%}
        <a href="{% url 'recipe_update' pk=recipe.id%}" class="update-btn">Update Recipe</a>
        <a href="{% url 'recipe_delete' pk=recipe.id%}" class="delete-btn">Delete Recipe</a>
        {% endif %}
    </div>
        
{% endblock content %}
    

templates/home.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<main>
    <section id="recipes">
        <div class="recipe-list">
            
            {% for recipe in recipes %}
            <div class="card">
                <div class="card-img">
                    
                        <img src="{{recipe.image.url}}">
                    </a>
                </div>
                <div class="card-detail">
                    <a href="{% url 'recipe_detail' pk=recipe.id%}">
                        <h3>{{recipe.name}}</h3>
                    </a>
                    <p>{{recipe.detail|truncatewords:20}}</p>
                </div>
            </div>
            {% endfor %}
                
        </div>      
    </section>
</main>

{%endblock content%}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="form">
        <form action="" method="post">
            <h1>Login</h1>
            {% csrf_token %}
            {{ form}}
            <input type="submit" value="Sign Up" class="btn btn-primary mt-4">
        </form>
    </div>
{% endblock content %}
    

templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="form">
        <form action="" method="post">
            <h1>Sign Up</h1>
            {% csrf_token %}
            {{ form|crispy}}
            <input type="submit" value="Sign Up" class="btn btn-primary">
        </form>
    </div>
{% endblock content %}
    

templates/update.html
{% extends 'base.html' %}
{% block content %}
   <form action="" method="post">
    {% csrf_token %}
    <h2>Update Recipe</h2>
    {{ form }}
    <input type="submit" value="Update" class="btn-primary">
   </form>
{% endblock content %}
    